### PR TITLE
Migrate from Jbuilder to Dune

### PR DESCRIPTION
**Pull request by TypesLogicsCats**
This commit migrates the project from Jbuilder to Dune, as Jbuilder will be
discontinued in July.

When switching from Jbuilder to Dune, I encountered warnings about record labels not listed in patterns, which I surpressed in the `dune` file. Do you want me to add `; _` to the record patterns to deal with the warning?

I also got a warning in `examples/simple_example.ml` because of an unused variable `i`, which I replaced with a wildcard.

Note that when I run `make` while using OCaml 4.08, I get deprecation notices regarding the Format module, but the package seems to install anyway. This issue seems to be unrelated to migration from Jbuilder to Dune.

### CODE REVIEW

**Comment by mjambon** [comment]
Looking great. Thank you very much.

> When switching from Jbuilder to Dune, I encountered warnings about record labels not listed in patterns, which I surpressed in the dune file. Do you want me to add ; _ to the record patterns to deal with the warning?

Please do so. I think it's better to stick with default warnings as much as possible (at least in a small code base like this one).

> Note that when I run make while using OCaml 4.08, I get deprecation notices regarding the Format module, but the package seems to install anyway. This issue seems to be unrelated to migration from Jbuilder to Dune.

We should fix this separately. Would you mind filing an issue for that? Otherwise I'll do it.

**Comment by TypesLogicsCats** [comment]
Oh yeah, sorry, I forgot to mention:

You have a List module that shadows the List module of the standard library while replacing certain functions with tail-recursive versions. However, none of these functions seem to be used in the rest of the code, and when I use Dune, I get a warning about unused names. However, if I were to remove the module, then someone might use the functions later and end up using the versions from the standard library. Should I keep or remove the module?

**Comment by mjambon** [comment]
This `List` module isn't part of the module interface (not in the .mli), so we can do whatever we want. I see that `List.rev_split` is used in one spot but `List.map` and `List.split` are unused. I'd suggest removing the unused functions, and taking `rev_split` out of the `List` submodule which can now be removed.

**Comment by TypesLogicsCats** [comment]
I have removed the List module.

**Comment by TypesLogicsCats** [comment]
(Don't forget to publish the changes on OPAM.)

**Comment by mjambon** [comment]
I don't have time for it. I will only do the minimum to help transfer the repo to [ocaml-community](https://github.com/ocaml-community) or to another account or organization.

**Pull request merged**
